---

  fasta_reference:
    fasta:
      checksum: 1915dd4d059445de6202ff5a6ad905ef
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta
    fasta_index:
      checksum: d9761a52554b0f5cb60e02c30b91afec
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai
  
  sites:
    checksum: 14cc588a271951ac1806f9be895fb51f
    path: hastings/Homo_sapiens_assembly38.known_indels.vcf.gz
    type: file
    url: file:/data/ref_data/wp3/hastings/Homo_sapiens_assembly38.known_indels.vcf.gz

  bwa:
    amb:
      checksum: e338073a7ddea5642676c2cdd56b11c4
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb
    ann:
      checksum: 52d5364585390855658c3b42ed62658e
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann
    bwt:
      checksum: 95524ac216194f0af57dabae31efcd1e
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt
    pac:
      checksum: ff28da3cc95336e413ca4b3439b1d486
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac
    sa:
      checksum: 85d033f622db1470a525ca083f5e4fb2
      path: hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa
      type: file
      url: file:/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa
 
  exomedepth_call:
    exonsfile:
      checksum: f3ed2cb6706065422ef72d307d82452f  
      path: hastings/exons_GRCh38_ensembl109.txt
      type: file
      url: file:/data/ref_data/wp3/hastings/exons_GRCh38_ensembl109.txt
    genesfile:
      checksum: a72c9c1608e07cd8d3a1bfd1f65106ee
      path: hastings/genes_GRCh38_ensembl109.txt
      type: file
      url: file:/data/ref_data/wp3/hastings/genes_GRCh38_ensembl109.txt