REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp3_te/design_and_ref_files
APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp3_te/apptainer_cache

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp3_te/hastings_rd_wes_{{PIPELINE_VERSION}}/hydra-genetics

resources: config/resources.miarka.yaml

samples: config/samples.tsv

units: config/units.tsv

output: config/output_list.json

default_container: '{{APPTAINER_CACHE}}/hydragenetics__common_3.1.1.sif'

modules:
  alignment: v0.7.0
  annotation: v1.2.0
  cnv_sv: v1.0.2
  compression: v2.1.0
  filtering: v1.1.0
  misc: v0.2.0
  parabricks: v1.2.0
  prealignment: v1.4.0
  qc: v0.6.0
  references: e71ee62
  snv_indels: v1.3.1

reference:
  annovar: '{{REFERENCE_DATA}}/hastings/annovar/'
  coverage_bed: '{{REFERENCE_DATA}}/hastings/hastings_coverage_20250109.bed'
  design_bed: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed'
  design_intervals: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list'
  fai: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.fai'
  fasta: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta'
  genepanels: '{{REFERENCE_DATA}}/hastings/genepanels.list'
  sites: '{{REFERENCE_DATA}}/hastings/Homo_sapiens_assembly38.known_indels.vcf.gz'
  skip_chrs:
  - chrM

trimmer_software: fastp_pe

aligner: bwa_cpu

snp_caller: deepvariant_cpu

automap:
  build: hg38
  container: '{{APPTAINER_CACHE}}/hydragenetics__automap_1.2.sif'
  extra: --DP 10 --minsize 3 --chrX
  outdir: cnv_sv/automap

bcftools_view_deepvariant:
  regions: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed'

bcftools_hardfilter_exomedepth:
  exclude: "'BF<=0'"

bwa_mem:
  amb: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.amb'
  ann: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.ann'
  bwt: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.bwt'
  container: '{{APPTAINER_CACHE}}/hydragenetics__bwa_0.7.15.sif'
  extra: -K 100000000
  pac: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.pac'
  sa: '{{REFERENCE_DATA}}/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta.sa'

create_cov_excel:
  covLimits: 10 20 30

deepmosaic_draw:
  container: '{{APPTAINER_CACHE}}/library_____sanglee8888__deepmosaic__deepmosaic_sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e.sif'

deepmosaic_predict:
  container: '{{APPTAINER_CACHE}}/library_____sanglee8888__deepmosaic__deepmosaic_sha256.28b3dd3b3ab1daa63b53d627c3fba3e6b4da38447ccdb9c7abc073718ff9453e.sif'

deepvariant:
  bed: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted_20bp_pad.bed'
  container: '{{APPTAINER_CACHE}}/google__deepvariant_1.6.1.sif'
  model_type: WES
  output_gvcf: true

deepsomatic_t_only:
  container: '{{APPTAINER_CACHE}}/google__deepsomatic_1.8.0.sif'
  extra: "--use_default_pon_filtering=true make_examples_extra_args='vsc_min_fraction_snps=0.029,vsc_min_fraction_indels=0.05' " #--use_default_pon_filtering=true or --pon_filtering='pon.vcf' --process_somatic=true or ''
  model: 'WGS_TUMOR_ONLY' # WGS,WES,PACBIO,ONT,FFPE_WGS,FFPE_WES,WGS_TUMOR_ONLY,PACBIO_TUMOR_ONLY,ONT_TUMOR_ONLY

exomedepth_call:
  bedfile: '{{REFERENCE_DATA}}/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed'
  container: '{{APPTAINER_CACHE}}/hydragenetics__exomedepth_1.1.15.sif'
  exonsfile: '{{REFERENCE_DATA}}/hastings/exons_GRCh38_ensembl109.txt'
  genesfile: '{{REFERENCE_DATA}}/hastings/genes_GRCh38_ensembl109.txt'
  genome_version: hg38

exomedepth_export:
  container: '{{APPTAINER_CACHE}}/hydragenetics__exomedepth_1.1.15.sif'

fastp_pe:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastp_0.20.1.sif'
  extra: --trim_poly_g --qualified_quality_phred 15 --unqualified_percent_limit 40
    --n_base_limit 5 --length_required 15

fastqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastqc_0.11.9.sif'

glnexus_peddy:
  configfile: DeepVariantWES
  container: '{{APPTAINER_CACHE}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif'

glnexus_trio:
  configfile: DeepVariantWES
  container: '{{APPTAINER_CACHE}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif'

melt:
  container: "{{APPTAINER_CACHE}}/MELT_v2.2.2.sif"
  bed: "{{REFERENCE_DATA}}/hastings/melt/Hg38.genes.bed"
  extra: ""
  mei: "{{REFERENCE_DATA}}/hastings/melt/mei_list.txt"

mosaicforecast_phasing:
  container: '{{APPTAINER_CACHE}}/yanmei__mosaicforecast_hg38_0.0.1.sif'
  f_format: 'bam' # cram/bam
  umap: '/usr/local/bin/k24.umap.wg.bw'

mosaicforecast_readlevel:
  container: '{{APPTAINER_CACHE}}/yanmei__mosaicforecast_hg38_0.0.1.sif'
  f_format: 'bam' # cram/bam
  umap: '/usr/local/bin/k24.umap.wg.bw'

mosaicforecast_genotype_prediction:
  container: '{{APPTAINER_CACHE}}/yanmei__mosaicforecast_hg38_0.0.1.sif'
  model_trainedSNP: '{{REFERENCE_DATA}}/hastings/150xRFmodel_addRMSK_Refine.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)
  model_trainedINS: '{{REFERENCE_DATA}}/hastings/insertions_250x.RF.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)
  model_trainedDEL: '{{REFERENCE_DATA}}/hastings/deletions_250x.RF.rds' # 200xRFmodel_addRMSK_Refine.rds or deletions_250x.RF.rds(phase) or insertions_250x.RF.rds(phase)
  model_typeSNP: 'Refine'  # phase/refine
  model_typeINDEL: 'Phase'  # phase/refine

mosdepth_bed:
  container: '{{APPTAINER_CACHE}}/hydragenetics__mosdepth_0.3.2.sif'
  extra: ''

multiqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics__multiqc_1.21.sif'
  reports:
    DNA:
      config: config/multiqc_config_DNA.yaml
      included_unit_types:
      - N
      qc_files:
      - qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip
      - qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip
      - qc/mosdepth_bed_design/{sample}_{type}.mosdepth.summary.txt
      - qc/mosdepth_bed_design/{sample}_{type}.mosdepth.region.dist.txt
      - qc/mosdepth_bed_design/{sample}_{type}.mosdepth.global.dist.txt
      - qc/peddy/peddy.peddy.ped
      - qc/peddy/peddy.background_pca.json
      - qc/peddy/peddy.ped_check.csv
      - qc/peddy/peddy.sex_check.csv
      - qc/peddy/peddy.het_check.csv
      - qc/peddy/peddy_sex_check_mqc.tsv
      - qc/peddy/peddy_rel_check_mqc.tsv
      - qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt
      - qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt
      - qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics
      - qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt
      - qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt
      - qc/samtools_stats/{sample}_{type}.samtools-stats.txt
      - qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt

pbrun_deepvariant:
  container: '{{APPTAINER_CACHE}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.1-1.sif'
  extra: '--use-wes-model --mode shortread --disable-use-window-selector-model --gvcf '

pbrun_fq2bam:
  container: '{{APPTAINER_CACHE}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.1-1.sif'
  extra: ''

peddy:
  config: config/peddy_mqc.yaml
  container: '{{APPTAINER_CACHE}}/hydragenetics__peddy_0.4.8.sif'
  extra: '--sites hg38 '

picard_collect_alignment_summary_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_duplication_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_gc_bias_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_hs_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_insert_size_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_multiple_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_wgs_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_mark_duplicates:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.4.sif'


spring:
  container: '{{APPTAINER_CACHE}}/hydragenetics__spring_1.1.1.sif'

upd:
  container: '{{APPTAINER_CACHE}}/hydragenetics__upd_0.1.1.sif'
  extra: '--vep '

vep_trio:
  container: '{{APPTAINER_CACHE}}/ensemblorg__ensembl-vep_release_110.1.sif'
  extra: '--assembly GRCh38 --check_existing --pick --max_af '
  vep_cache: '{{REFERENCE_DATA}}/hastings/VEP/'

vt_decompose:
  container: '{{APPTAINER_CACHE}}/hydragenetics__vt_2015.11.10.sif'

