---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "core"

bwa_mem:
  mem_mb: 122880
  mem_per_cpu: 6144
  threads: 8

deepmosaic_draw:
  mem_mb: 40960
  mem_per_cpu: 4096
  threads: 10
  time: "12:00:00"

deepmosaic_predict:
  mem_mb: 40960
  mem_per_cpu: 4096
  threads: 10
  time: "12:00:00"

deepvariant:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10
  time: "12:00:00"

deepsomatic_t_only:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10
  time: "12:00:00"

fastp_pe:
  threads: 1
  mem_mb: 6144
  mem_per_cpu: 6144

fastqc:
  threads: 2
  mem_mb: 12288
  mem_per_cpu: 6144

glnexus:
  threads: 20

melt:
  threads: 10
  mem_mb: 40960
  mem_per_cpu: 4096

mosaicforecast:
  threads: 2
  mem_mb: 8200
  mem_per_cpu: 4096

mosdepth_bed:
  mem_mb: 36864
  threads: 4

pbrun_fq2bam:
  gres: "--gres=gres:gpu:l40s:3"
  mem_mb: 160000
  mem_per_cpu: 5000
  partition: "gpu"
  threads: 32

pbrun_deepvariant:
  gres: "--gres=gres:gpu:l40s:3"
  mem_mb: 160000
  mem_per_cpu: 5000
  partition: "gpu"
  threads: 32

peddy:
  threads: 8

samtools_sort:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

samtools_view:
  mem_mb: 61440
  mem_per_cpu: 6144
  threads: 10

spring:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8
  partition: "core"

vep:
  threads: 4